-- MySQL Script generated by MySQL Workbench
-- Thu Dec 31 15:35:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monblogperso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monblogperso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monblogperso` DEFAULT CHARACTER SET utf8 ;
USE `monblogperso` ;

-- -----------------------------------------------------
-- Table `monblogperso`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`categories` (
  `categorie_id` INT NOT NULL AUTO_INCREMENT,
  `categorie_name` VARCHAR(45) NULL,
  PRIMARY KEY (`categorie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monblogperso`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`comments` (
  `comment_id` INT NOT NULL,
  `comment_text` TEXT NULL,
  `comment_date` DATETIME NULL,
  PRIMARY KEY (`comment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monblogperso`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  `date` DATETIME NULL,
  `categorie_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articles_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `monblogperso`.`categories` (`categorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `monblogperso`.`comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_categories1_idx` ON `monblogperso`.`articles` (`categorie_id` ASC) ;

CREATE INDEX `fk_articles_comments1_idx` ON `monblogperso`.`articles` (`comment_id` ASC) ;


-- -----------------------------------------------------
-- Table `monblogperso`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(200) NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monblogperso`.`articles_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`articles_images` (
  `article_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `image_id`),
  CONSTRAINT `fk_articles_has_images_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `monblogperso`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_images_images1`
    FOREIGN KEY (`image_id`)
    REFERENCES `monblogperso`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_images_images1_idx` ON `monblogperso`.`articles_images` (`image_id` ASC) ;

CREATE INDEX `fk_articles_has_images_articles1_idx` ON `monblogperso`.`articles_images` (`article_id` ASC) ;


-- -----------------------------------------------------
-- Table `monblogperso`.`editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`editor` (
  `editor_id` INT NOT NULL AUTO_INCREMENT,
  `editor_name` VARCHAR(100) NULL,
  `editor_password` VARCHAR(45) NULL,
  PRIMARY KEY (`editor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monblogperso`.`articles_editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monblogperso`.`articles_editor` (
  `articles_id` INT NOT NULL,
  `editor_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `editor_id`),
  CONSTRAINT `fk_articles_has_editor_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `monblogperso`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_editor_editor1`
    FOREIGN KEY (`editor_id`)
    REFERENCES `monblogperso`.`editor` (`editor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_editor_editor1_idx` ON `monblogperso`.`articles_editor` (`editor_id` ASC) ;

CREATE INDEX `fk_articles_has_editor_articles1_idx` ON `monblogperso`.`articles_editor` (`articles_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
